# Generated by Django 4.2.6 on 2023-10-26 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200304_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='times_rated',
            field=models.IntegerField(default=0),
        ),
    ]
